### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by ekdnam** [CSE-210-Team-6/shuttlecraft#47]
The UI is trivial and there are a lot of chances of improving.

**Comment by ekdnam** [comment]
1. the color palette has changed to match that of twitter (white and blue)
2. the support for dark theme is discontinued
3. the background colors for posts and notifications are changed
4. ensure that the content is centered while viewing the website on a small screen (mobile)
5. change the background color for the messages sent
6. fix the styles for composer and mini composer
7. refactor - break secrets.css into smaller files
8. update preferences page UI
9. navbar color changes - color is navyblue for the tab which is linked to our current page
10. the font is now helvetica
11. changing the button input style
12. changing background color and adding box shadow for settings

**Comment by ekdnam** [comment]
https://github.com/CSE-210-Team-6/shuttlecraft/pull/53

**Comment by kashishvjain** [comment]
All UI Changes have been merged
